version: "3.9"
services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app           # source code
      - /app/node_modules # keeps host deps isolated
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true  # reliable file watching in Docker
    command: sh -c "npm install && npm run dev"
